### ISSUE TITLE
Use with influxdb from grafana?

### ISSUE THREAD

**Issue by hpmueller1971** [tedpearson/edf-importer#3]
Hi,

just discovered this on Friday, awesome! OSCAR is great, but nerds prefer server-side-apps :-)

Could you give us some pointers, if it is possible to use just influxdb+grafana (i've never used them both before)...?

Also, have you looked at the possibility to use the bluetooth-interface in the AirSense11 (i don't use it yet, because the mobile-cloud-stuff is currently disabled on mine, and i don't want to "wake it up")...?

I'm not sure, if the actual therapy-data is transmitted over it (from what i've read, the android-app only show's the data after a day or two, so it seems that always goes over the ResMed-Mothership), but with the TestDrive-Function it's possible to try out different pressures and comfort-features like EPR, so there are at least some basic functions available via ble.

Could be interesting to have my Home Assistant yell at me, "it's too dry, get up and refill the tank" :-)

Kinds Regards,

/hp

**Comment by tedpearson** [comment]
Hi @hpmueller1971!

It's certainly possible to use influxdb instead of victoriametrics. This tool should work just fine with influxdb as well. You'd need to create your own dashboard using influxql/flux queries.

As far as using bluetooth is concerned, per one of the OSCAR devs, the ResMed bluetooth functionality is extremely limited and does not include the ability to download any data from the device: https://www.apneaboard.com/forums/Thread-AirSense-11-no-longer-sending-data-over-Bluetooth?pid=443862#pid443862

It's certainly inconvenient to only access the data by removing the SD card, but that's the only vector I'm aware of for accessing the data. I've read up on "wifi SD cards" which seem to be pretty basic devices that require either an app or just run an HTTP server to allow downloading data. It didn't seem like a good solution to pursue to me.

As for data about the humidifier, there is no data on the SD card about humidity, so there would be no way to alert on that condition.
